sonar.projectKey=marcus
sonar.projectName=marcus
sonar.projectVersion=1.0
sonar.sources=.
sonar.language=py
sonar.sourceEncoding=UTF-8
sonar.python.coverage.reportPaths=coverage.xml
sonar.login=${SONAR_TOKEN}
sonar.host.url=${SONAR_URL}
